name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        node: [ 14, 16, 18 ]
    name: Test Nodejs v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: chrvadala/github-actions/nodejs-test-library-action@v1
        with:
          NODE_VERSION: ${{ matrix.node }}
      - name: Publish Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-nodejs-v${{ matrix.node }}-${{ matrix.os }}
          parallel: true

  finish:
    name: Finish
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
